CREATE TABLE TABLEA (
   A_ID 		BIGINT NOT NULL,
   A_VALUE0 	VARCHAR(64),
   A_VALUE1 	VARCHAR(64),
   A_VALUE2 	VARCHAR(64),
   A_VALUE3 	VARCHAR(64),
   A_VALUE4 	VARCHAR(64),
   A_VALUE5 	VARCHAR(64),
   PRIMARY KEY (A_ID)
);

CREATE TABLE TABLEB (
   B_ID 		BIGINT NOT NULL,
   B_A_ID 		BIGINT NOT NULL REFERENCES TABLEA (A_ID),
   B_VALUE0 	VARCHAR(64),
   B_VALUE1 	VARCHAR(64),
   B_VALUE2 	VARCHAR(64),
   B_VALUE3 	VARCHAR(64),
   B_VALUE4 	VARCHAR(64),
   B_VALUE5 	VARCHAR(64),
   PRIMARY KEY (B_ID, B_A_ID)
);