#!/usr/bin/env python
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------
# Copyright (C) 2012 by H-Store Project
# Brown University
# Massachusetts Institute of Technology
# Yale University
# 
# http://hstore.cs.brown.edu/ 
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
# -----------------------------------------------------------------------
from __future__ import with_statement

import os
import sys
import subprocess
from glob import glob

THIRD_PARTY_DIR = "third_party/java/jars"
BUILD_DIR = "obj/release/prod"

JVM_ARGS = [
    "-client",
    "-Xmx128m",
    "-Dlog4j.configuration=log4j.properties",
    "-ea", 
]
JVM_CLASSPATH = [ BUILD_DIR ] + glob("%s/*.jar" % THIRD_PARTY_DIR)
JVM_TARGET = "edu.brown.terminal.HStoreTerminal"

## ==============================================
## main
## ==============================================
if __name__ == '__main__':
    
    cmd = "java %s -classpath %s %s %s" % (\
        " ".join(JVM_ARGS), \
        ":".join(JVM_CLASSPATH), \
        JVM_TARGET, \
        " ".join(sys.argv[1:]))
    print(cmd)
    try:
        p = subprocess.Popen(cmd, shell=True)
        p.wait()
    except:
        pass
    sys.exit(p.returncode)
## MAIN