// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ca/evanjones/table/Table.proto

package ca.evanjones.table;

public final class Table {
  private Table() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Account extends
      com.google.protobuf.GeneratedMessage {
    // Use Account.newBuilder() to construct.
    private Account() {
      initFields();
    }
    private Account(boolean noInit) {}
    
    private static final Account defaultInstance;
    public static Account getDefaultInstance() {
      return defaultInstance;
    }
    
    public Account getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_Account_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_Account_fieldAccessorTable;
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // required int32 balance = 2;
    public static final int BALANCE_FIELD_NUMBER = 2;
    private boolean hasBalance;
    private int balance_ = 0;
    public boolean hasBalance() { return hasBalance; }
    public int getBalance() { return balance_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasBalance) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasBalance()) {
        output.writeInt32(2, getBalance());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasBalance()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getBalance());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.table.Table.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.table.Table.Account prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.table.Table.Account result;
      
      // Construct using ca.evanjones.table.Table.Account.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.table.Table.Account();
        return builder;
      }
      
      protected ca.evanjones.table.Table.Account internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.table.Table.Account();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.table.Table.Account.getDescriptor();
      }
      
      public ca.evanjones.table.Table.Account getDefaultInstanceForType() {
        return ca.evanjones.table.Table.Account.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.table.Table.Account build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.table.Table.Account buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.table.Table.Account buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ca.evanjones.table.Table.Account returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.table.Table.Account) {
          return mergeFrom((ca.evanjones.table.Table.Account)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.table.Table.Account other) {
        if (other == ca.evanjones.table.Table.Account.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasBalance()) {
          setBalance(other.getBalance());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 16: {
              setBalance(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // required int32 balance = 2;
      public boolean hasBalance() {
        return result.hasBalance();
      }
      public int getBalance() {
        return result.getBalance();
      }
      public Builder setBalance(int value) {
        result.hasBalance = true;
        result.balance_ = value;
        return this;
      }
      public Builder clearBalance() {
        result.hasBalance = false;
        result.balance_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.table.Account)
    }
    
    static {
      defaultInstance = new Account(true);
      ca.evanjones.table.Table.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.table.Account)
  }
  
  public static final class ReadRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use ReadRequest.newBuilder() to construct.
    private ReadRequest() {
      initFields();
    }
    private ReadRequest(boolean noInit) {}
    
    private static final ReadRequest defaultInstance;
    public static ReadRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ReadRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_ReadRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_ReadRequest_fieldAccessorTable;
    }
    
    // repeated int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> id_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getIdList() {
      return id_;
    }
    public int getIdCount() { return id_.size(); }
    public int getId(int index) {
      return id_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int element : getIdList()) {
        output.writeInt32(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int element : getIdList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.table.Table.ReadRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.ReadRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.ReadRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.ReadRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.ReadRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.ReadRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.ReadRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.ReadRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.ReadRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.ReadRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.table.Table.ReadRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.table.Table.ReadRequest result;
      
      // Construct using ca.evanjones.table.Table.ReadRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.table.Table.ReadRequest();
        return builder;
      }
      
      protected ca.evanjones.table.Table.ReadRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.table.Table.ReadRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.table.Table.ReadRequest.getDescriptor();
      }
      
      public ca.evanjones.table.Table.ReadRequest getDefaultInstanceForType() {
        return ca.evanjones.table.Table.ReadRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.table.Table.ReadRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.table.Table.ReadRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.table.Table.ReadRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.id_ != java.util.Collections.EMPTY_LIST) {
          result.id_ =
            java.util.Collections.unmodifiableList(result.id_);
        }
        ca.evanjones.table.Table.ReadRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.table.Table.ReadRequest) {
          return mergeFrom((ca.evanjones.table.Table.ReadRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.table.Table.ReadRequest other) {
        if (other == ca.evanjones.table.Table.ReadRequest.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (result.id_.isEmpty()) {
            result.id_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.id_.addAll(other.id_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              addId(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addId(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated int32 id = 1;
      public java.util.List<java.lang.Integer> getIdList() {
        return java.util.Collections.unmodifiableList(result.id_);
      }
      public int getIdCount() {
        return result.getIdCount();
      }
      public int getId(int index) {
        return result.getId(index);
      }
      public Builder setId(int index, int value) {
        result.id_.set(index, value);
        return this;
      }
      public Builder addId(int value) {
        if (result.id_.isEmpty()) {
          result.id_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.id_.add(value);
        return this;
      }
      public Builder addAllId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.id_.isEmpty()) {
          result.id_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.id_);
        return this;
      }
      public Builder clearId() {
        result.id_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.table.ReadRequest)
    }
    
    static {
      defaultInstance = new ReadRequest(true);
      ca.evanjones.table.Table.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.table.ReadRequest)
  }
  
  public static final class ReadResult extends
      com.google.protobuf.GeneratedMessage {
    // Use ReadResult.newBuilder() to construct.
    private ReadResult() {
      initFields();
    }
    private ReadResult(boolean noInit) {}
    
    private static final ReadResult defaultInstance;
    public static ReadResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public ReadResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_ReadResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_ReadResult_fieldAccessorTable;
    }
    
    // repeated .ca.evanjones.table.Account account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private java.util.List<ca.evanjones.table.Table.Account> account_ =
      java.util.Collections.emptyList();
    public java.util.List<ca.evanjones.table.Table.Account> getAccountList() {
      return account_;
    }
    public int getAccountCount() { return account_.size(); }
    public ca.evanjones.table.Table.Account getAccount(int index) {
      return account_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (ca.evanjones.table.Table.Account element : getAccountList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (ca.evanjones.table.Table.Account element : getAccountList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (ca.evanjones.table.Table.Account element : getAccountList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.table.Table.ReadResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.ReadResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.ReadResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.ReadResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.ReadResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.ReadResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.ReadResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.ReadResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.ReadResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.ReadResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.table.Table.ReadResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.table.Table.ReadResult result;
      
      // Construct using ca.evanjones.table.Table.ReadResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.table.Table.ReadResult();
        return builder;
      }
      
      protected ca.evanjones.table.Table.ReadResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.table.Table.ReadResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.table.Table.ReadResult.getDescriptor();
      }
      
      public ca.evanjones.table.Table.ReadResult getDefaultInstanceForType() {
        return ca.evanjones.table.Table.ReadResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.table.Table.ReadResult build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.table.Table.ReadResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.table.Table.ReadResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.account_ != java.util.Collections.EMPTY_LIST) {
          result.account_ =
            java.util.Collections.unmodifiableList(result.account_);
        }
        ca.evanjones.table.Table.ReadResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.table.Table.ReadResult) {
          return mergeFrom((ca.evanjones.table.Table.ReadResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.table.Table.ReadResult other) {
        if (other == ca.evanjones.table.Table.ReadResult.getDefaultInstance()) return this;
        if (!other.account_.isEmpty()) {
          if (result.account_.isEmpty()) {
            result.account_ = new java.util.ArrayList<ca.evanjones.table.Table.Account>();
          }
          result.account_.addAll(other.account_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              ca.evanjones.table.Table.Account.Builder subBuilder = ca.evanjones.table.Table.Account.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAccount(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .ca.evanjones.table.Account account = 1;
      public java.util.List<ca.evanjones.table.Table.Account> getAccountList() {
        return java.util.Collections.unmodifiableList(result.account_);
      }
      public int getAccountCount() {
        return result.getAccountCount();
      }
      public ca.evanjones.table.Table.Account getAccount(int index) {
        return result.getAccount(index);
      }
      public Builder setAccount(int index, ca.evanjones.table.Table.Account value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.account_.set(index, value);
        return this;
      }
      public Builder setAccount(int index, ca.evanjones.table.Table.Account.Builder builderForValue) {
        result.account_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAccount(ca.evanjones.table.Table.Account value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.account_.isEmpty()) {
          result.account_ = new java.util.ArrayList<ca.evanjones.table.Table.Account>();
        }
        result.account_.add(value);
        return this;
      }
      public Builder addAccount(ca.evanjones.table.Table.Account.Builder builderForValue) {
        if (result.account_.isEmpty()) {
          result.account_ = new java.util.ArrayList<ca.evanjones.table.Table.Account>();
        }
        result.account_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAccount(
          java.lang.Iterable<? extends ca.evanjones.table.Table.Account> values) {
        if (result.account_.isEmpty()) {
          result.account_ = new java.util.ArrayList<ca.evanjones.table.Table.Account>();
        }
        super.addAll(values, result.account_);
        return this;
      }
      public Builder clearAccount() {
        result.account_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.table.ReadResult)
    }
    
    static {
      defaultInstance = new ReadResult(true);
      ca.evanjones.table.Table.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.table.ReadResult)
  }
  
  public static final class WriteRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use WriteRequest.newBuilder() to construct.
    private WriteRequest() {
      initFields();
    }
    private WriteRequest(boolean noInit) {}
    
    private static final WriteRequest defaultInstance;
    public static WriteRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public WriteRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_WriteRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_WriteRequest_fieldAccessorTable;
    }
    
    // repeated .ca.evanjones.table.Account account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private java.util.List<ca.evanjones.table.Table.Account> account_ =
      java.util.Collections.emptyList();
    public java.util.List<ca.evanjones.table.Table.Account> getAccountList() {
      return account_;
    }
    public int getAccountCount() { return account_.size(); }
    public ca.evanjones.table.Table.Account getAccount(int index) {
      return account_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (ca.evanjones.table.Table.Account element : getAccountList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (ca.evanjones.table.Table.Account element : getAccountList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (ca.evanjones.table.Table.Account element : getAccountList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.table.Table.WriteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.WriteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.WriteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.WriteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.WriteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.WriteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.WriteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.WriteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.WriteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.WriteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.table.Table.WriteRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.table.Table.WriteRequest result;
      
      // Construct using ca.evanjones.table.Table.WriteRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.table.Table.WriteRequest();
        return builder;
      }
      
      protected ca.evanjones.table.Table.WriteRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.table.Table.WriteRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.table.Table.WriteRequest.getDescriptor();
      }
      
      public ca.evanjones.table.Table.WriteRequest getDefaultInstanceForType() {
        return ca.evanjones.table.Table.WriteRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.table.Table.WriteRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.table.Table.WriteRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.table.Table.WriteRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.account_ != java.util.Collections.EMPTY_LIST) {
          result.account_ =
            java.util.Collections.unmodifiableList(result.account_);
        }
        ca.evanjones.table.Table.WriteRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.table.Table.WriteRequest) {
          return mergeFrom((ca.evanjones.table.Table.WriteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.table.Table.WriteRequest other) {
        if (other == ca.evanjones.table.Table.WriteRequest.getDefaultInstance()) return this;
        if (!other.account_.isEmpty()) {
          if (result.account_.isEmpty()) {
            result.account_ = new java.util.ArrayList<ca.evanjones.table.Table.Account>();
          }
          result.account_.addAll(other.account_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              ca.evanjones.table.Table.Account.Builder subBuilder = ca.evanjones.table.Table.Account.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAccount(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .ca.evanjones.table.Account account = 1;
      public java.util.List<ca.evanjones.table.Table.Account> getAccountList() {
        return java.util.Collections.unmodifiableList(result.account_);
      }
      public int getAccountCount() {
        return result.getAccountCount();
      }
      public ca.evanjones.table.Table.Account getAccount(int index) {
        return result.getAccount(index);
      }
      public Builder setAccount(int index, ca.evanjones.table.Table.Account value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.account_.set(index, value);
        return this;
      }
      public Builder setAccount(int index, ca.evanjones.table.Table.Account.Builder builderForValue) {
        result.account_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAccount(ca.evanjones.table.Table.Account value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.account_.isEmpty()) {
          result.account_ = new java.util.ArrayList<ca.evanjones.table.Table.Account>();
        }
        result.account_.add(value);
        return this;
      }
      public Builder addAccount(ca.evanjones.table.Table.Account.Builder builderForValue) {
        if (result.account_.isEmpty()) {
          result.account_ = new java.util.ArrayList<ca.evanjones.table.Table.Account>();
        }
        result.account_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAccount(
          java.lang.Iterable<? extends ca.evanjones.table.Table.Account> values) {
        if (result.account_.isEmpty()) {
          result.account_ = new java.util.ArrayList<ca.evanjones.table.Table.Account>();
        }
        super.addAll(values, result.account_);
        return this;
      }
      public Builder clearAccount() {
        result.account_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.table.WriteRequest)
    }
    
    static {
      defaultInstance = new WriteRequest(true);
      ca.evanjones.table.Table.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.table.WriteRequest)
  }
  
  public static final class WriteResult extends
      com.google.protobuf.GeneratedMessage {
    // Use WriteResult.newBuilder() to construct.
    private WriteResult() {
      initFields();
    }
    private WriteResult(boolean noInit) {}
    
    private static final WriteResult defaultInstance;
    public static WriteResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public WriteResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_WriteResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.table.Table.internal_static_ca_evanjones_table_WriteResult_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.table.Table.WriteResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.WriteResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.WriteResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.table.Table.WriteResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.WriteResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.WriteResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.table.Table.WriteResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.WriteResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.table.Table.WriteResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.table.Table.WriteResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.table.Table.WriteResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.table.Table.WriteResult result;
      
      // Construct using ca.evanjones.table.Table.WriteResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.table.Table.WriteResult();
        return builder;
      }
      
      protected ca.evanjones.table.Table.WriteResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.table.Table.WriteResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.table.Table.WriteResult.getDescriptor();
      }
      
      public ca.evanjones.table.Table.WriteResult getDefaultInstanceForType() {
        return ca.evanjones.table.Table.WriteResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.table.Table.WriteResult build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.table.Table.WriteResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.table.Table.WriteResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ca.evanjones.table.Table.WriteResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.table.Table.WriteResult) {
          return mergeFrom((ca.evanjones.table.Table.WriteResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.table.Table.WriteResult other) {
        if (other == ca.evanjones.table.Table.WriteResult.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.table.WriteResult)
    }
    
    static {
      defaultInstance = new WriteResult(true);
      ca.evanjones.table.Table.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.table.WriteResult)
  }
  
  public static abstract class TableService
      implements com.google.protobuf.Service {
    protected TableService() {}
    
    public interface Interface {
      public abstract void read(
          com.google.protobuf.RpcController controller,
          ca.evanjones.table.Table.ReadRequest request,
          com.google.protobuf.RpcCallback<ca.evanjones.table.Table.ReadResult> done);
      
      public abstract void write(
          com.google.protobuf.RpcController controller,
          ca.evanjones.table.Table.WriteRequest request,
          com.google.protobuf.RpcCallback<ca.evanjones.table.Table.WriteResult> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TableService() {
        @Override
        public  void read(
            com.google.protobuf.RpcController controller,
            ca.evanjones.table.Table.ReadRequest request,
            com.google.protobuf.RpcCallback<ca.evanjones.table.Table.ReadResult> done) {
          impl.read(controller, request, done);
        }
        
        @Override
        public  void write(
            com.google.protobuf.RpcController controller,
            ca.evanjones.table.Table.WriteRequest request,
            com.google.protobuf.RpcCallback<ca.evanjones.table.Table.WriteResult> done) {
          impl.write(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.read(controller, (ca.evanjones.table.Table.ReadRequest)request);
            case 1:
              return impl.write(controller, (ca.evanjones.table.Table.WriteRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return ca.evanjones.table.Table.ReadRequest.getDefaultInstance();
            case 1:
              return ca.evanjones.table.Table.WriteRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return ca.evanjones.table.Table.ReadResult.getDefaultInstance();
            case 1:
              return ca.evanjones.table.Table.WriteResult.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void read(
        com.google.protobuf.RpcController controller,
        ca.evanjones.table.Table.ReadRequest request,
        com.google.protobuf.RpcCallback<ca.evanjones.table.Table.ReadResult> done);
    
    public abstract void write(
        com.google.protobuf.RpcController controller,
        ca.evanjones.table.Table.WriteRequest request,
        com.google.protobuf.RpcCallback<ca.evanjones.table.Table.WriteResult> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return ca.evanjones.table.Table.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.read(controller, (ca.evanjones.table.Table.ReadRequest)request,
            com.google.protobuf.RpcUtil.<ca.evanjones.table.Table.ReadResult>specializeCallback(
              done));
          return;
        case 1:
          this.write(controller, (ca.evanjones.table.Table.WriteRequest)request,
            com.google.protobuf.RpcUtil.<ca.evanjones.table.Table.WriteResult>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return ca.evanjones.table.Table.ReadRequest.getDefaultInstance();
        case 1:
          return ca.evanjones.table.Table.WriteRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return ca.evanjones.table.Table.ReadResult.getDefaultInstance();
        case 1:
          return ca.evanjones.table.Table.WriteResult.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends ca.evanjones.table.Table.TableService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void read(
          com.google.protobuf.RpcController controller,
          ca.evanjones.table.Table.ReadRequest request,
          com.google.protobuf.RpcCallback<ca.evanjones.table.Table.ReadResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          ca.evanjones.table.Table.ReadResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            ca.evanjones.table.Table.ReadResult.class,
            ca.evanjones.table.Table.ReadResult.getDefaultInstance()));
      }
      
      public  void write(
          com.google.protobuf.RpcController controller,
          ca.evanjones.table.Table.WriteRequest request,
          com.google.protobuf.RpcCallback<ca.evanjones.table.Table.WriteResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          ca.evanjones.table.Table.WriteResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            ca.evanjones.table.Table.WriteResult.class,
            ca.evanjones.table.Table.WriteResult.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public ca.evanjones.table.Table.ReadResult read(
          com.google.protobuf.RpcController controller,
          ca.evanjones.table.Table.ReadRequest request)
          throws com.google.protobuf.ServiceException;
      
      public ca.evanjones.table.Table.WriteResult write(
          com.google.protobuf.RpcController controller,
          ca.evanjones.table.Table.WriteRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public ca.evanjones.table.Table.ReadResult read(
          com.google.protobuf.RpcController controller,
          ca.evanjones.table.Table.ReadRequest request)
          throws com.google.protobuf.ServiceException {
        return (ca.evanjones.table.Table.ReadResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          ca.evanjones.table.Table.ReadResult.getDefaultInstance());
      }
      
      
      public ca.evanjones.table.Table.WriteResult write(
          com.google.protobuf.RpcController controller,
          ca.evanjones.table.Table.WriteRequest request)
          throws com.google.protobuf.ServiceException {
        return (ca.evanjones.table.Table.WriteResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          ca.evanjones.table.Table.WriteResult.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_table_Account_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_table_Account_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_table_ReadRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_table_ReadRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_table_ReadResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_table_ReadResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_table_WriteRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_table_WriteRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_table_WriteResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_table_WriteResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036ca/evanjones/table/Table.proto\022\022ca.eva" +
      "njones.table\032$ca/evanjones/protorpc/Prot" +
      "ocol.proto\"&\n\007Account\022\n\n\002id\030\001 \002(\005\022\017\n\007bal" +
      "ance\030\002 \002(\005\"\031\n\013ReadRequest\022\n\n\002id\030\001 \003(\005\":\n" +
      "\nReadResult\022,\n\007account\030\001 \003(\0132\033.ca.evanjo" +
      "nes.table.Account\"<\n\014WriteRequest\022,\n\007acc" +
      "ount\030\001 \003(\0132\033.ca.evanjones.table.Account\"" +
      "\r\n\013WriteResult2\243\001\n\014TableService\022G\n\004Read\022" +
      "\037.ca.evanjones.table.ReadRequest\032\036.ca.ev" +
      "anjones.table.ReadResult\022J\n\005Write\022 .ca.e",
      "vanjones.table.WriteRequest\032\037.ca.evanjon" +
      "es.table.WriteResult"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ca_evanjones_table_Account_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ca_evanjones_table_Account_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_table_Account_descriptor,
              new java.lang.String[] { "Id", "Balance", },
              ca.evanjones.table.Table.Account.class,
              ca.evanjones.table.Table.Account.Builder.class);
          internal_static_ca_evanjones_table_ReadRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ca_evanjones_table_ReadRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_table_ReadRequest_descriptor,
              new java.lang.String[] { "Id", },
              ca.evanjones.table.Table.ReadRequest.class,
              ca.evanjones.table.Table.ReadRequest.Builder.class);
          internal_static_ca_evanjones_table_ReadResult_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ca_evanjones_table_ReadResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_table_ReadResult_descriptor,
              new java.lang.String[] { "Account", },
              ca.evanjones.table.Table.ReadResult.class,
              ca.evanjones.table.Table.ReadResult.Builder.class);
          internal_static_ca_evanjones_table_WriteRequest_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ca_evanjones_table_WriteRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_table_WriteRequest_descriptor,
              new java.lang.String[] { "Account", },
              ca.evanjones.table.Table.WriteRequest.class,
              ca.evanjones.table.Table.WriteRequest.Builder.class);
          internal_static_ca_evanjones_table_WriteResult_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_ca_evanjones_table_WriteResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_table_WriteResult_descriptor,
              new java.lang.String[] { },
              ca.evanjones.table.Table.WriteResult.class,
              ca.evanjones.table.Table.WriteResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.evanjones.protorpc.Protocol.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
