/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_brown_hashing_ConsistentHasher */

#ifndef _Included_edu_brown_hashing_ConsistentHasher
#define _Included_edu_brown_hashing_ConsistentHasher
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOG */
/* Inaccessible static: _00024assertionsDisabled */
/* Inaccessible static: _00024assertionsDisabled */
/*
 * Class:     edu_brown_hashing_ConsistentHasher
 * Method:    nativeCreate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_edu_brown_hashing_ConsistentHasher_nativeCreate
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_brown_hashing_ConsistentHasher
 * Method:    nativeDestroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_brown_hashing_ConsistentHasher_nativeDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_brown_hashing_ConsistentHasher
 * Method:    nativeHashinate
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_edu_brown_hashing_ConsistentHasher_nativeHashinate
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
