// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ca/evanjones/db/Transactions.proto

package ca.evanjones.db;

public final class Transactions {
  private Transactions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    PREPARED(0, 0),
    ABORT_DEADLOCK(1, 1),
    ABORT_USER(2, 2),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static Status valueOf(int value) {
      switch (value) {
        case 0: return PREPARED;
        case 1: return ABORT_DEADLOCK;
        case 2: return ABORT_USER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ca.evanjones.db.Transactions.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Status[] VALUES = {
      PREPARED, ABORT_DEADLOCK, ABORT_USER, 
    };
    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private Status(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      ca.evanjones.db.Transactions.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:ca.evanjones.db.Status)
  }
  
  public static final class TransactionRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use TransactionRequest.newBuilder() to construct.
    private TransactionRequest() {
      initFields();
    }
    private TransactionRequest(boolean noInit) {}
    
    private static final TransactionRequest defaultInstance;
    public static TransactionRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public TransactionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.db.Transactions.internal_static_ca_evanjones_db_TransactionRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.db.Transactions.internal_static_ca_evanjones_db_TransactionRequest_fieldAccessorTable;
    }
    
    // required int32 transaction_id = 1;
    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    private boolean hasTransactionId;
    private int transactionId_ = 0;
    public boolean hasTransactionId() { return hasTransactionId; }
    public int getTransactionId() { return transactionId_; }
    
    // required .protorpc.RpcRequest request = 2;
    public static final int REQUEST_FIELD_NUMBER = 2;
    private boolean hasRequest;
    private ca.evanjones.protorpc.Protocol.RpcRequest request_;
    public boolean hasRequest() { return hasRequest; }
    public ca.evanjones.protorpc.Protocol.RpcRequest getRequest() { return request_; }
    
    private void initFields() {
      request_ = ca.evanjones.protorpc.Protocol.RpcRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasTransactionId) return false;
      if (!hasRequest) return false;
      if (!getRequest().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTransactionId()) {
        output.writeInt32(1, getTransactionId());
      }
      if (hasRequest()) {
        output.writeMessage(2, getRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTransactionId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getTransactionId());
      }
      if (hasRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.db.Transactions.TransactionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.db.Transactions.TransactionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.db.Transactions.TransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.db.Transactions.TransactionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.db.Transactions.TransactionRequest result;
      
      // Construct using ca.evanjones.db.Transactions.TransactionRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.db.Transactions.TransactionRequest();
        return builder;
      }
      
      protected ca.evanjones.db.Transactions.TransactionRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.db.Transactions.TransactionRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.db.Transactions.TransactionRequest.getDescriptor();
      }
      
      public ca.evanjones.db.Transactions.TransactionRequest getDefaultInstanceForType() {
        return ca.evanjones.db.Transactions.TransactionRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.db.Transactions.TransactionRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.db.Transactions.TransactionRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.db.Transactions.TransactionRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ca.evanjones.db.Transactions.TransactionRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.db.Transactions.TransactionRequest) {
          return mergeFrom((ca.evanjones.db.Transactions.TransactionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.db.Transactions.TransactionRequest other) {
        if (other == ca.evanjones.db.Transactions.TransactionRequest.getDefaultInstance()) return this;
        if (other.hasTransactionId()) {
          setTransactionId(other.getTransactionId());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTransactionId(input.readInt32());
              break;
            }
            case 18: {
              ca.evanjones.protorpc.Protocol.RpcRequest.Builder subBuilder = ca.evanjones.protorpc.Protocol.RpcRequest.newBuilder();
              if (hasRequest()) {
                subBuilder.mergeFrom(getRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 transaction_id = 1;
      public boolean hasTransactionId() {
        return result.hasTransactionId();
      }
      public int getTransactionId() {
        return result.getTransactionId();
      }
      public Builder setTransactionId(int value) {
        result.hasTransactionId = true;
        result.transactionId_ = value;
        return this;
      }
      public Builder clearTransactionId() {
        result.hasTransactionId = false;
        result.transactionId_ = 0;
        return this;
      }
      
      // required .protorpc.RpcRequest request = 2;
      public boolean hasRequest() {
        return result.hasRequest();
      }
      public ca.evanjones.protorpc.Protocol.RpcRequest getRequest() {
        return result.getRequest();
      }
      public Builder setRequest(ca.evanjones.protorpc.Protocol.RpcRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRequest = true;
        result.request_ = value;
        return this;
      }
      public Builder setRequest(ca.evanjones.protorpc.Protocol.RpcRequest.Builder builderForValue) {
        result.hasRequest = true;
        result.request_ = builderForValue.build();
        return this;
      }
      public Builder mergeRequest(ca.evanjones.protorpc.Protocol.RpcRequest value) {
        if (result.hasRequest() &&
            result.request_ != ca.evanjones.protorpc.Protocol.RpcRequest.getDefaultInstance()) {
          result.request_ =
            ca.evanjones.protorpc.Protocol.RpcRequest.newBuilder(result.request_).mergeFrom(value).buildPartial();
        } else {
          result.request_ = value;
        }
        result.hasRequest = true;
        return this;
      }
      public Builder clearRequest() {
        result.hasRequest = false;
        result.request_ = ca.evanjones.protorpc.Protocol.RpcRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.db.TransactionRequest)
    }
    
    static {
      defaultInstance = new TransactionRequest(true);
      ca.evanjones.db.Transactions.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.db.TransactionRequest)
  }
  
  public static final class TransactionResult extends
      com.google.protobuf.GeneratedMessage {
    // Use TransactionResult.newBuilder() to construct.
    private TransactionResult() {
      initFields();
    }
    private TransactionResult(boolean noInit) {}
    
    private static final TransactionResult defaultInstance;
    public static TransactionResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public TransactionResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.db.Transactions.internal_static_ca_evanjones_db_TransactionResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.db.Transactions.internal_static_ca_evanjones_db_TransactionResult_fieldAccessorTable;
    }
    
    // required .ca.evanjones.db.Status status = 1 [default = PREPARED];
    public static final int STATUS_FIELD_NUMBER = 1;
    private boolean hasStatus;
    private ca.evanjones.db.Transactions.Status status_;
    public boolean hasStatus() { return hasStatus; }
    public ca.evanjones.db.Transactions.Status getStatus() { return status_; }
    
    // optional bytes response = 2;
    public static final int RESPONSE_FIELD_NUMBER = 2;
    private boolean hasResponse;
    private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasResponse() { return hasResponse; }
    public com.google.protobuf.ByteString getResponse() { return response_; }
    
    private void initFields() {
      status_ = ca.evanjones.db.Transactions.Status.PREPARED;
    }
    public final boolean isInitialized() {
      if (!hasStatus) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasStatus()) {
        output.writeEnum(1, getStatus().getNumber());
      }
      if (hasResponse()) {
        output.writeBytes(2, getResponse());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getStatus().getNumber());
      }
      if (hasResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResponse());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.db.Transactions.TransactionResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.db.Transactions.TransactionResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.db.Transactions.TransactionResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.db.Transactions.TransactionResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.db.Transactions.TransactionResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.db.Transactions.TransactionResult result;
      
      // Construct using ca.evanjones.db.Transactions.TransactionResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.db.Transactions.TransactionResult();
        return builder;
      }
      
      protected ca.evanjones.db.Transactions.TransactionResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.db.Transactions.TransactionResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.db.Transactions.TransactionResult.getDescriptor();
      }
      
      public ca.evanjones.db.Transactions.TransactionResult getDefaultInstanceForType() {
        return ca.evanjones.db.Transactions.TransactionResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.db.Transactions.TransactionResult build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.db.Transactions.TransactionResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.db.Transactions.TransactionResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ca.evanjones.db.Transactions.TransactionResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.db.Transactions.TransactionResult) {
          return mergeFrom((ca.evanjones.db.Transactions.TransactionResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.db.Transactions.TransactionResult other) {
        if (other == ca.evanjones.db.Transactions.TransactionResult.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ca.evanjones.db.Transactions.Status value = ca.evanjones.db.Transactions.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setStatus(value);
              }
              break;
            }
            case 18: {
              setResponse(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required .ca.evanjones.db.Status status = 1 [default = PREPARED];
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public ca.evanjones.db.Transactions.Status getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(ca.evanjones.db.Transactions.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = ca.evanjones.db.Transactions.Status.PREPARED;
        return this;
      }
      
      // optional bytes response = 2;
      public boolean hasResponse() {
        return result.hasResponse();
      }
      public com.google.protobuf.ByteString getResponse() {
        return result.getResponse();
      }
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasResponse = true;
        result.response_ = value;
        return this;
      }
      public Builder clearResponse() {
        result.hasResponse = false;
        result.response_ = getDefaultInstance().getResponse();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.db.TransactionResult)
    }
    
    static {
      defaultInstance = new TransactionResult(true);
      ca.evanjones.db.Transactions.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.db.TransactionResult)
  }
  
  public static final class FinishRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use FinishRequest.newBuilder() to construct.
    private FinishRequest() {
      initFields();
    }
    private FinishRequest(boolean noInit) {}
    
    private static final FinishRequest defaultInstance;
    public static FinishRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public FinishRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.db.Transactions.internal_static_ca_evanjones_db_FinishRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.db.Transactions.internal_static_ca_evanjones_db_FinishRequest_fieldAccessorTable;
    }
    
    // required int32 transaction_id = 1;
    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    private boolean hasTransactionId;
    private int transactionId_ = 0;
    public boolean hasTransactionId() { return hasTransactionId; }
    public int getTransactionId() { return transactionId_; }
    
    // required bool commit = 2;
    public static final int COMMIT_FIELD_NUMBER = 2;
    private boolean hasCommit;
    private boolean commit_ = false;
    public boolean hasCommit() { return hasCommit; }
    public boolean getCommit() { return commit_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasTransactionId) return false;
      if (!hasCommit) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTransactionId()) {
        output.writeInt32(1, getTransactionId());
      }
      if (hasCommit()) {
        output.writeBool(2, getCommit());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTransactionId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getTransactionId());
      }
      if (hasCommit()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getCommit());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.db.Transactions.FinishRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.db.Transactions.FinishRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.db.Transactions.FinishRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.db.Transactions.FinishRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.db.Transactions.FinishRequest result;
      
      // Construct using ca.evanjones.db.Transactions.FinishRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.db.Transactions.FinishRequest();
        return builder;
      }
      
      protected ca.evanjones.db.Transactions.FinishRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.db.Transactions.FinishRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.db.Transactions.FinishRequest.getDescriptor();
      }
      
      public ca.evanjones.db.Transactions.FinishRequest getDefaultInstanceForType() {
        return ca.evanjones.db.Transactions.FinishRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.db.Transactions.FinishRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.db.Transactions.FinishRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.db.Transactions.FinishRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ca.evanjones.db.Transactions.FinishRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.db.Transactions.FinishRequest) {
          return mergeFrom((ca.evanjones.db.Transactions.FinishRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.db.Transactions.FinishRequest other) {
        if (other == ca.evanjones.db.Transactions.FinishRequest.getDefaultInstance()) return this;
        if (other.hasTransactionId()) {
          setTransactionId(other.getTransactionId());
        }
        if (other.hasCommit()) {
          setCommit(other.getCommit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTransactionId(input.readInt32());
              break;
            }
            case 16: {
              setCommit(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required int32 transaction_id = 1;
      public boolean hasTransactionId() {
        return result.hasTransactionId();
      }
      public int getTransactionId() {
        return result.getTransactionId();
      }
      public Builder setTransactionId(int value) {
        result.hasTransactionId = true;
        result.transactionId_ = value;
        return this;
      }
      public Builder clearTransactionId() {
        result.hasTransactionId = false;
        result.transactionId_ = 0;
        return this;
      }
      
      // required bool commit = 2;
      public boolean hasCommit() {
        return result.hasCommit();
      }
      public boolean getCommit() {
        return result.getCommit();
      }
      public Builder setCommit(boolean value) {
        result.hasCommit = true;
        result.commit_ = value;
        return this;
      }
      public Builder clearCommit() {
        result.hasCommit = false;
        result.commit_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.db.FinishRequest)
    }
    
    static {
      defaultInstance = new FinishRequest(true);
      ca.evanjones.db.Transactions.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.db.FinishRequest)
  }
  
  public static final class FinishResult extends
      com.google.protobuf.GeneratedMessage {
    // Use FinishResult.newBuilder() to construct.
    private FinishResult() {
      initFields();
    }
    private FinishResult(boolean noInit) {}
    
    private static final FinishResult defaultInstance;
    public static FinishResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public FinishResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.db.Transactions.internal_static_ca_evanjones_db_FinishResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.db.Transactions.internal_static_ca_evanjones_db_FinishResult_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.db.Transactions.FinishResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.db.Transactions.FinishResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.db.Transactions.FinishResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.db.Transactions.FinishResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.db.Transactions.FinishResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.db.Transactions.FinishResult result;
      
      // Construct using ca.evanjones.db.Transactions.FinishResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.db.Transactions.FinishResult();
        return builder;
      }
      
      protected ca.evanjones.db.Transactions.FinishResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.db.Transactions.FinishResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.db.Transactions.FinishResult.getDescriptor();
      }
      
      public ca.evanjones.db.Transactions.FinishResult getDefaultInstanceForType() {
        return ca.evanjones.db.Transactions.FinishResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.db.Transactions.FinishResult build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.db.Transactions.FinishResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.db.Transactions.FinishResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ca.evanjones.db.Transactions.FinishResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.db.Transactions.FinishResult) {
          return mergeFrom((ca.evanjones.db.Transactions.FinishResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.db.Transactions.FinishResult other) {
        if (other == ca.evanjones.db.Transactions.FinishResult.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.db.FinishResult)
    }
    
    static {
      defaultInstance = new FinishResult(true);
      ca.evanjones.db.Transactions.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.db.FinishResult)
  }
  
  public static abstract class TransactionService
      implements com.google.protobuf.Service {
    protected TransactionService() {}
    
    public interface Interface {
      public abstract void request(
          com.google.protobuf.RpcController controller,
          ca.evanjones.db.Transactions.TransactionRequest request,
          com.google.protobuf.RpcCallback<ca.evanjones.db.Transactions.TransactionResult> done);
      
      public abstract void finish(
          com.google.protobuf.RpcController controller,
          ca.evanjones.db.Transactions.FinishRequest request,
          com.google.protobuf.RpcCallback<ca.evanjones.db.Transactions.FinishResult> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TransactionService() {
        @Override
        public  void request(
            com.google.protobuf.RpcController controller,
            ca.evanjones.db.Transactions.TransactionRequest request,
            com.google.protobuf.RpcCallback<ca.evanjones.db.Transactions.TransactionResult> done) {
          impl.request(controller, request, done);
        }
        
        @Override
        public  void finish(
            com.google.protobuf.RpcController controller,
            ca.evanjones.db.Transactions.FinishRequest request,
            com.google.protobuf.RpcCallback<ca.evanjones.db.Transactions.FinishResult> done) {
          impl.finish(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.request(controller, (ca.evanjones.db.Transactions.TransactionRequest)request);
            case 1:
              return impl.finish(controller, (ca.evanjones.db.Transactions.FinishRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return ca.evanjones.db.Transactions.TransactionRequest.getDefaultInstance();
            case 1:
              return ca.evanjones.db.Transactions.FinishRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return ca.evanjones.db.Transactions.TransactionResult.getDefaultInstance();
            case 1:
              return ca.evanjones.db.Transactions.FinishResult.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void request(
        com.google.protobuf.RpcController controller,
        ca.evanjones.db.Transactions.TransactionRequest request,
        com.google.protobuf.RpcCallback<ca.evanjones.db.Transactions.TransactionResult> done);
    
    public abstract void finish(
        com.google.protobuf.RpcController controller,
        ca.evanjones.db.Transactions.FinishRequest request,
        com.google.protobuf.RpcCallback<ca.evanjones.db.Transactions.FinishResult> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return ca.evanjones.db.Transactions.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.request(controller, (ca.evanjones.db.Transactions.TransactionRequest)request,
            com.google.protobuf.RpcUtil.<ca.evanjones.db.Transactions.TransactionResult>specializeCallback(
              done));
          return;
        case 1:
          this.finish(controller, (ca.evanjones.db.Transactions.FinishRequest)request,
            com.google.protobuf.RpcUtil.<ca.evanjones.db.Transactions.FinishResult>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return ca.evanjones.db.Transactions.TransactionRequest.getDefaultInstance();
        case 1:
          return ca.evanjones.db.Transactions.FinishRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return ca.evanjones.db.Transactions.TransactionResult.getDefaultInstance();
        case 1:
          return ca.evanjones.db.Transactions.FinishResult.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends ca.evanjones.db.Transactions.TransactionService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void request(
          com.google.protobuf.RpcController controller,
          ca.evanjones.db.Transactions.TransactionRequest request,
          com.google.protobuf.RpcCallback<ca.evanjones.db.Transactions.TransactionResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          ca.evanjones.db.Transactions.TransactionResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            ca.evanjones.db.Transactions.TransactionResult.class,
            ca.evanjones.db.Transactions.TransactionResult.getDefaultInstance()));
      }
      
      public  void finish(
          com.google.protobuf.RpcController controller,
          ca.evanjones.db.Transactions.FinishRequest request,
          com.google.protobuf.RpcCallback<ca.evanjones.db.Transactions.FinishResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          ca.evanjones.db.Transactions.FinishResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            ca.evanjones.db.Transactions.FinishResult.class,
            ca.evanjones.db.Transactions.FinishResult.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public ca.evanjones.db.Transactions.TransactionResult request(
          com.google.protobuf.RpcController controller,
          ca.evanjones.db.Transactions.TransactionRequest request)
          throws com.google.protobuf.ServiceException;
      
      public ca.evanjones.db.Transactions.FinishResult finish(
          com.google.protobuf.RpcController controller,
          ca.evanjones.db.Transactions.FinishRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public ca.evanjones.db.Transactions.TransactionResult request(
          com.google.protobuf.RpcController controller,
          ca.evanjones.db.Transactions.TransactionRequest request)
          throws com.google.protobuf.ServiceException {
        return (ca.evanjones.db.Transactions.TransactionResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          ca.evanjones.db.Transactions.TransactionResult.getDefaultInstance());
      }
      
      
      public ca.evanjones.db.Transactions.FinishResult finish(
          com.google.protobuf.RpcController controller,
          ca.evanjones.db.Transactions.FinishRequest request)
          throws com.google.protobuf.ServiceException {
        return (ca.evanjones.db.Transactions.FinishResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          ca.evanjones.db.Transactions.FinishResult.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_db_TransactionRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_db_TransactionRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_db_TransactionResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_db_TransactionResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_db_FinishRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_db_FinishRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_db_FinishResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_db_FinishResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"ca/evanjones/db/Transactions.proto\022\017ca" +
      ".evanjones.db\032$ca/evanjones/protorpc/Pro" +
      "tocol.proto\"S\n\022TransactionRequest\022\026\n\016tra" +
      "nsaction_id\030\001 \002(\005\022%\n\007request\030\002 \002(\0132\024.pro" +
      "torpc.RpcRequest\"X\n\021TransactionResult\0221\n" +
      "\006status\030\001 \002(\0162\027.ca.evanjones.db.Status:\010" +
      "PREPARED\022\020\n\010response\030\002 \001(\014\"7\n\rFinishRequ" +
      "est\022\026\n\016transaction_id\030\001 \002(\005\022\016\n\006commit\030\002 " +
      "\002(\010\"\016\n\014FinishResult*:\n\006Status\022\014\n\010PREPARE" +
      "D\020\000\022\022\n\016ABORT_DEADLOCK\020\001\022\016\n\nABORT_USER\020\0022",
      "\261\001\n\022TransactionService\022R\n\007Request\022#.ca.e" +
      "vanjones.db.TransactionRequest\032\".ca.evan" +
      "jones.db.TransactionResult\022G\n\006Finish\022\036.c" +
      "a.evanjones.db.FinishRequest\032\035.ca.evanjo" +
      "nes.db.FinishResult"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ca_evanjones_db_TransactionRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ca_evanjones_db_TransactionRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_db_TransactionRequest_descriptor,
              new java.lang.String[] { "TransactionId", "Request", },
              ca.evanjones.db.Transactions.TransactionRequest.class,
              ca.evanjones.db.Transactions.TransactionRequest.Builder.class);
          internal_static_ca_evanjones_db_TransactionResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ca_evanjones_db_TransactionResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_db_TransactionResult_descriptor,
              new java.lang.String[] { "Status", "Response", },
              ca.evanjones.db.Transactions.TransactionResult.class,
              ca.evanjones.db.Transactions.TransactionResult.Builder.class);
          internal_static_ca_evanjones_db_FinishRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ca_evanjones_db_FinishRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_db_FinishRequest_descriptor,
              new java.lang.String[] { "TransactionId", "Commit", },
              ca.evanjones.db.Transactions.FinishRequest.class,
              ca.evanjones.db.Transactions.FinishRequest.Builder.class);
          internal_static_ca_evanjones_db_FinishResult_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ca_evanjones_db_FinishResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_db_FinishResult_descriptor,
              new java.lang.String[] { },
              ca.evanjones.db.Transactions.FinishResult.class,
              ca.evanjones.db.Transactions.FinishResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.evanjones.protorpc.Protocol.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
