package edu.brown.markov.features;

import java.util.regex.Pattern;

import org.voltdb.catalog.Procedure;

import edu.brown.utils.ClassUtil;
import edu.brown.utils.PartitionEstimator;

public abstract class FeatureUtil {
    
    protected final static String DELIMITER = "-";
    protected final static String SUFFIX = "Feature";
    protected final static int SUFFIX_LENGTH = SUFFIX.length();
    protected final static Pattern PREFIX_SPLITTER = Pattern.compile(DELIMITER);
    protected final static String PREFIX_FORMAT = "%s" + DELIMITER + "%02d";

    /**
     * For the given feature key, return a new instance of that AbstractFeature
     * @param key
     * @param catalog_proc
     * @param p_estimator
     * @return
     */
    public static AbstractFeature getFeatureForKey(String key, Procedure catalog_proc, PartitionEstimator p_estimator) {
        assert(key != null);
        assert(catalog_proc != null);
        assert(p_estimator != null);
        
        String featureName = FeatureUtil.getFeatureKeyPrefix(key) + "Feature";
        Class<?> featureClass = ClassUtil.getClass(featureName); 
        AbstractFeature f = (AbstractFeature)ClassUtil.newInstance(
                                featureClass,
                                new Object[]{ p_estimator, catalog_proc },
                                new Class[] { PartitionEstimator.class, Procedure.class });
        return (f);
    }

    /**
     * Return the prefix that will be used for all attributes generated by the given Feature class
     * @param feature_class
     * @return
     */
    public static final String getFeatureKeyPrefix(Class<? extends AbstractFeature> feature_class) {
        String prefix = feature_class.getSimpleName(); 
        return (prefix.substring(0, prefix.length() - SUFFIX_LENGTH));
    }

    /**
     * 
     * @param feature_key
     * @return
     */
    public static final String getFeatureKeyPrefix(String feature_key) {
        return (PREFIX_SPLITTER.split(feature_key, 1)[0]);
    }
    
    
}
