// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ca/evanjones/protorpc/Example.proto

package ca.evanjones.protorpc;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Values extends
      com.google.protobuf.GeneratedMessage {
    // Use Values.newBuilder() to construct.
    private Values() {
      initFields();
    }
    private Values(boolean noInit) {}
    
    private static final Values defaultInstance;
    public static Values getDefaultInstance() {
      return defaultInstance;
    }
    
    public Values getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.protorpc.Example.internal_static_ca_evanjones_protorpc_Values_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.protorpc.Example.internal_static_ca_evanjones_protorpc_Values_fieldAccessorTable;
    }
    
    // repeated int32 values = 1;
    public static final int VALUES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> values_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getValuesList() {
      return values_;
    }
    public int getValuesCount() { return values_.size(); }
    public int getValues(int index) {
      return values_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int element : getValuesList()) {
        output.writeInt32(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int element : getValuesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.protorpc.Example.Values parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.protorpc.Example.Values parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.protorpc.Example.Values parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.protorpc.Example.Values parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.protorpc.Example.Values parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.protorpc.Example.Values parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.protorpc.Example.Values parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.protorpc.Example.Values parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.protorpc.Example.Values parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.protorpc.Example.Values parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.protorpc.Example.Values prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.protorpc.Example.Values result;
      
      // Construct using ca.evanjones.protorpc.Example.Values.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.protorpc.Example.Values();
        return builder;
      }
      
      protected ca.evanjones.protorpc.Example.Values internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.protorpc.Example.Values();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.protorpc.Example.Values.getDescriptor();
      }
      
      public ca.evanjones.protorpc.Example.Values getDefaultInstanceForType() {
        return ca.evanjones.protorpc.Example.Values.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.protorpc.Example.Values build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.protorpc.Example.Values buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.protorpc.Example.Values buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.values_ != java.util.Collections.EMPTY_LIST) {
          result.values_ =
            java.util.Collections.unmodifiableList(result.values_);
        }
        ca.evanjones.protorpc.Example.Values returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.protorpc.Example.Values) {
          return mergeFrom((ca.evanjones.protorpc.Example.Values)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.protorpc.Example.Values other) {
        if (other == ca.evanjones.protorpc.Example.Values.getDefaultInstance()) return this;
        if (!other.values_.isEmpty()) {
          if (result.values_.isEmpty()) {
            result.values_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.values_.addAll(other.values_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              addValues(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addValues(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated int32 values = 1;
      public java.util.List<java.lang.Integer> getValuesList() {
        return java.util.Collections.unmodifiableList(result.values_);
      }
      public int getValuesCount() {
        return result.getValuesCount();
      }
      public int getValues(int index) {
        return result.getValues(index);
      }
      public Builder setValues(int index, int value) {
        result.values_.set(index, value);
        return this;
      }
      public Builder addValues(int value) {
        if (result.values_.isEmpty()) {
          result.values_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.values_.add(value);
        return this;
      }
      public Builder addAllValues(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.values_.isEmpty()) {
          result.values_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.values_);
        return this;
      }
      public Builder clearValues() {
        result.values_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.protorpc.Values)
    }
    
    static {
      defaultInstance = new Values(true);
      ca.evanjones.protorpc.Example.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.protorpc.Values)
  }
  
  public static final class StatisticsResult extends
      com.google.protobuf.GeneratedMessage {
    // Use StatisticsResult.newBuilder() to construct.
    private StatisticsResult() {
      initFields();
    }
    private StatisticsResult(boolean noInit) {}
    
    private static final StatisticsResult defaultInstance;
    public static StatisticsResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public StatisticsResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.evanjones.protorpc.Example.internal_static_ca_evanjones_protorpc_StatisticsResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.evanjones.protorpc.Example.internal_static_ca_evanjones_protorpc_StatisticsResult_fieldAccessorTable;
    }
    
    // required int32 sum = 1;
    public static final int SUM_FIELD_NUMBER = 1;
    private boolean hasSum;
    private int sum_ = 0;
    public boolean hasSum() { return hasSum; }
    public int getSum() { return sum_; }
    
    // required double average = 2;
    public static final int AVERAGE_FIELD_NUMBER = 2;
    private boolean hasAverage;
    private double average_ = 0D;
    public boolean hasAverage() { return hasAverage; }
    public double getAverage() { return average_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasSum) return false;
      if (!hasAverage) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSum()) {
        output.writeInt32(1, getSum());
      }
      if (hasAverage()) {
        output.writeDouble(2, getAverage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSum()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getSum());
      }
      if (hasAverage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, getAverage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ca.evanjones.protorpc.Example.StatisticsResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.protorpc.Example.StatisticsResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.protorpc.Example.StatisticsResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ca.evanjones.protorpc.Example.StatisticsResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.protorpc.Example.StatisticsResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.protorpc.Example.StatisticsResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ca.evanjones.protorpc.Example.StatisticsResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.protorpc.Example.StatisticsResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ca.evanjones.protorpc.Example.StatisticsResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ca.evanjones.protorpc.Example.StatisticsResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ca.evanjones.protorpc.Example.StatisticsResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ca.evanjones.protorpc.Example.StatisticsResult result;
      
      // Construct using ca.evanjones.protorpc.Example.StatisticsResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ca.evanjones.protorpc.Example.StatisticsResult();
        return builder;
      }
      
      protected ca.evanjones.protorpc.Example.StatisticsResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ca.evanjones.protorpc.Example.StatisticsResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.evanjones.protorpc.Example.StatisticsResult.getDescriptor();
      }
      
      public ca.evanjones.protorpc.Example.StatisticsResult getDefaultInstanceForType() {
        return ca.evanjones.protorpc.Example.StatisticsResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ca.evanjones.protorpc.Example.StatisticsResult build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ca.evanjones.protorpc.Example.StatisticsResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ca.evanjones.protorpc.Example.StatisticsResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        ca.evanjones.protorpc.Example.StatisticsResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.evanjones.protorpc.Example.StatisticsResult) {
          return mergeFrom((ca.evanjones.protorpc.Example.StatisticsResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ca.evanjones.protorpc.Example.StatisticsResult other) {
        if (other == ca.evanjones.protorpc.Example.StatisticsResult.getDefaultInstance()) return this;
        if (other.hasSum()) {
          setSum(other.getSum());
        }
        if (other.hasAverage()) {
          setAverage(other.getAverage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setSum(input.readInt32());
              break;
            }
            case 17: {
              setAverage(input.readDouble());
              break;
            }
          }
        }
      }
      
      
      // required int32 sum = 1;
      public boolean hasSum() {
        return result.hasSum();
      }
      public int getSum() {
        return result.getSum();
      }
      public Builder setSum(int value) {
        result.hasSum = true;
        result.sum_ = value;
        return this;
      }
      public Builder clearSum() {
        result.hasSum = false;
        result.sum_ = 0;
        return this;
      }
      
      // required double average = 2;
      public boolean hasAverage() {
        return result.hasAverage();
      }
      public double getAverage() {
        return result.getAverage();
      }
      public Builder setAverage(double value) {
        result.hasAverage = true;
        result.average_ = value;
        return this;
      }
      public Builder clearAverage() {
        result.hasAverage = false;
        result.average_ = 0D;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ca.evanjones.protorpc.StatisticsResult)
    }
    
    static {
      defaultInstance = new StatisticsResult(true);
      ca.evanjones.protorpc.Example.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ca.evanjones.protorpc.StatisticsResult)
  }
  
  public static abstract class Statistics
      implements com.google.protobuf.Service {
    protected Statistics() {}
    
    public interface Interface {
      public abstract void calculate(
          com.google.protobuf.RpcController controller,
          ca.evanjones.protorpc.Example.Values request,
          com.google.protobuf.RpcCallback<ca.evanjones.protorpc.Example.StatisticsResult> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new Statistics() {
        @Override
        public  void calculate(
            com.google.protobuf.RpcController controller,
            ca.evanjones.protorpc.Example.Values request,
            com.google.protobuf.RpcCallback<ca.evanjones.protorpc.Example.StatisticsResult> done) {
          impl.calculate(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.calculate(controller, (ca.evanjones.protorpc.Example.Values)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return ca.evanjones.protorpc.Example.Values.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return ca.evanjones.protorpc.Example.StatisticsResult.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void calculate(
        com.google.protobuf.RpcController controller,
        ca.evanjones.protorpc.Example.Values request,
        com.google.protobuf.RpcCallback<ca.evanjones.protorpc.Example.StatisticsResult> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return ca.evanjones.protorpc.Example.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.calculate(controller, (ca.evanjones.protorpc.Example.Values)request,
            com.google.protobuf.RpcUtil.<ca.evanjones.protorpc.Example.StatisticsResult>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return ca.evanjones.protorpc.Example.Values.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return ca.evanjones.protorpc.Example.StatisticsResult.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends ca.evanjones.protorpc.Example.Statistics implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void calculate(
          com.google.protobuf.RpcController controller,
          ca.evanjones.protorpc.Example.Values request,
          com.google.protobuf.RpcCallback<ca.evanjones.protorpc.Example.StatisticsResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          ca.evanjones.protorpc.Example.StatisticsResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            ca.evanjones.protorpc.Example.StatisticsResult.class,
            ca.evanjones.protorpc.Example.StatisticsResult.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public ca.evanjones.protorpc.Example.StatisticsResult calculate(
          com.google.protobuf.RpcController controller,
          ca.evanjones.protorpc.Example.Values request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public ca.evanjones.protorpc.Example.StatisticsResult calculate(
          com.google.protobuf.RpcController controller,
          ca.evanjones.protorpc.Example.Values request)
          throws com.google.protobuf.ServiceException {
        return (ca.evanjones.protorpc.Example.StatisticsResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          ca.evanjones.protorpc.Example.StatisticsResult.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_protorpc_Values_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_protorpc_Values_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_evanjones_protorpc_StatisticsResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ca_evanjones_protorpc_StatisticsResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#ca/evanjones/protorpc/Example.proto\022\025c" +
      "a.evanjones.protorpc\"\030\n\006Values\022\016\n\006values" +
      "\030\001 \003(\005\"0\n\020StatisticsResult\022\013\n\003sum\030\001 \002(\005\022" +
      "\017\n\007average\030\002 \002(\0012a\n\nStatistics\022S\n\tCalcul" +
      "ate\022\035.ca.evanjones.protorpc.Values\032\'.ca." +
      "evanjones.protorpc.StatisticsResult"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ca_evanjones_protorpc_Values_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ca_evanjones_protorpc_Values_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_protorpc_Values_descriptor,
              new java.lang.String[] { "Values", },
              ca.evanjones.protorpc.Example.Values.class,
              ca.evanjones.protorpc.Example.Values.Builder.class);
          internal_static_ca_evanjones_protorpc_StatisticsResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ca_evanjones_protorpc_StatisticsResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ca_evanjones_protorpc_StatisticsResult_descriptor,
              new java.lang.String[] { "Sum", "Average", },
              ca.evanjones.protorpc.Example.StatisticsResult.class,
              ca.evanjones.protorpc.Example.StatisticsResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
