// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edu/brown/hstore/jvmsnapshot.proto

package edu.brown.hstore;

public final class Jvmsnapshot {
  private Jvmsnapshot() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class TransactionRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use TransactionRequest.newBuilder() to construct.
    private TransactionRequest() {
      initFields();
    }
    private TransactionRequest(boolean noInit) {}
    
    private static final TransactionRequest defaultInstance;
    public static TransactionRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public TransactionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.brown.hstore.Jvmsnapshot.internal_static_edu_brown_hstore_TransactionRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.brown.hstore.Jvmsnapshot.internal_static_edu_brown_hstore_TransactionRequest_fieldAccessorTable;
    }
    
    // required bytes request = 1;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private boolean hasRequest;
    private com.google.protobuf.ByteString request_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasRequest() { return hasRequest; }
    public com.google.protobuf.ByteString getRequest() { return request_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasRequest) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRequest()) {
        output.writeBytes(1, getRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.brown.hstore.Jvmsnapshot.TransactionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.brown.hstore.Jvmsnapshot.TransactionRequest result;
      
      // Construct using edu.brown.hstore.Jvmsnapshot.TransactionRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.brown.hstore.Jvmsnapshot.TransactionRequest();
        return builder;
      }
      
      protected edu.brown.hstore.Jvmsnapshot.TransactionRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.brown.hstore.Jvmsnapshot.TransactionRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.brown.hstore.Jvmsnapshot.TransactionRequest.getDescriptor();
      }
      
      public edu.brown.hstore.Jvmsnapshot.TransactionRequest getDefaultInstanceForType() {
        return edu.brown.hstore.Jvmsnapshot.TransactionRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.brown.hstore.Jvmsnapshot.TransactionRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.brown.hstore.Jvmsnapshot.TransactionRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.brown.hstore.Jvmsnapshot.TransactionRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.brown.hstore.Jvmsnapshot.TransactionRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.brown.hstore.Jvmsnapshot.TransactionRequest) {
          return mergeFrom((edu.brown.hstore.Jvmsnapshot.TransactionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.brown.hstore.Jvmsnapshot.TransactionRequest other) {
        if (other == edu.brown.hstore.Jvmsnapshot.TransactionRequest.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          setRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setRequest(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required bytes request = 1;
      public boolean hasRequest() {
        return result.hasRequest();
      }
      public com.google.protobuf.ByteString getRequest() {
        return result.getRequest();
      }
      public Builder setRequest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRequest = true;
        result.request_ = value;
        return this;
      }
      public Builder clearRequest() {
        result.hasRequest = false;
        result.request_ = getDefaultInstance().getRequest();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.brown.hstore.TransactionRequest)
    }
    
    static {
      defaultInstance = new TransactionRequest(true);
      edu.brown.hstore.Jvmsnapshot.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.brown.hstore.TransactionRequest)
  }
  
  public static final class TransactionResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use TransactionResponse.newBuilder() to construct.
    private TransactionResponse() {
      initFields();
    }
    private TransactionResponse(boolean noInit) {}
    
    private static final TransactionResponse defaultInstance;
    public static TransactionResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public TransactionResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.brown.hstore.Jvmsnapshot.internal_static_edu_brown_hstore_TransactionResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.brown.hstore.Jvmsnapshot.internal_static_edu_brown_hstore_TransactionResponse_fieldAccessorTable;
    }
    
    // required bytes output = 1;
    public static final int OUTPUT_FIELD_NUMBER = 1;
    private boolean hasOutput;
    private com.google.protobuf.ByteString output_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasOutput() { return hasOutput; }
    public com.google.protobuf.ByteString getOutput() { return output_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasOutput) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasOutput()) {
        output.writeBytes(1, getOutput());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasOutput()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOutput());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.brown.hstore.Jvmsnapshot.TransactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.brown.hstore.Jvmsnapshot.TransactionResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private edu.brown.hstore.Jvmsnapshot.TransactionResponse result;
      
      // Construct using edu.brown.hstore.Jvmsnapshot.TransactionResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.brown.hstore.Jvmsnapshot.TransactionResponse();
        return builder;
      }
      
      protected edu.brown.hstore.Jvmsnapshot.TransactionResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.brown.hstore.Jvmsnapshot.TransactionResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.brown.hstore.Jvmsnapshot.TransactionResponse.getDescriptor();
      }
      
      public edu.brown.hstore.Jvmsnapshot.TransactionResponse getDefaultInstanceForType() {
        return edu.brown.hstore.Jvmsnapshot.TransactionResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.brown.hstore.Jvmsnapshot.TransactionResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.brown.hstore.Jvmsnapshot.TransactionResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.brown.hstore.Jvmsnapshot.TransactionResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.brown.hstore.Jvmsnapshot.TransactionResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.brown.hstore.Jvmsnapshot.TransactionResponse) {
          return mergeFrom((edu.brown.hstore.Jvmsnapshot.TransactionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.brown.hstore.Jvmsnapshot.TransactionResponse other) {
        if (other == edu.brown.hstore.Jvmsnapshot.TransactionResponse.getDefaultInstance()) return this;
        if (other.hasOutput()) {
          setOutput(other.getOutput());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setOutput(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required bytes output = 1;
      public boolean hasOutput() {
        return result.hasOutput();
      }
      public com.google.protobuf.ByteString getOutput() {
        return result.getOutput();
      }
      public Builder setOutput(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOutput = true;
        result.output_ = value;
        return this;
      }
      public Builder clearOutput() {
        result.hasOutput = false;
        result.output_ = getDefaultInstance().getOutput();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.brown.hstore.TransactionResponse)
    }
    
    static {
      defaultInstance = new TransactionResponse(true);
      edu.brown.hstore.Jvmsnapshot.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.brown.hstore.TransactionResponse)
  }
  
  public static abstract class HStoreJVMSnapshotService
      implements com.google.protobuf.Service {
    protected HStoreJVMSnapshotService() {}
    
    public interface Interface {
      public abstract void execTransactionRequest(
          com.google.protobuf.RpcController controller,
          edu.brown.hstore.Jvmsnapshot.TransactionRequest request,
          com.google.protobuf.RpcCallback<edu.brown.hstore.Jvmsnapshot.TransactionResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new HStoreJVMSnapshotService() {
        @Override
        public  void execTransactionRequest(
            com.google.protobuf.RpcController controller,
            edu.brown.hstore.Jvmsnapshot.TransactionRequest request,
            com.google.protobuf.RpcCallback<edu.brown.hstore.Jvmsnapshot.TransactionResponse> done) {
          impl.execTransactionRequest(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.execTransactionRequest(controller, (edu.brown.hstore.Jvmsnapshot.TransactionRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.brown.hstore.Jvmsnapshot.TransactionRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return edu.brown.hstore.Jvmsnapshot.TransactionResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void execTransactionRequest(
        com.google.protobuf.RpcController controller,
        edu.brown.hstore.Jvmsnapshot.TransactionRequest request,
        com.google.protobuf.RpcCallback<edu.brown.hstore.Jvmsnapshot.TransactionResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return edu.brown.hstore.Jvmsnapshot.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.execTransactionRequest(controller, (edu.brown.hstore.Jvmsnapshot.TransactionRequest)request,
            com.google.protobuf.RpcUtil.<edu.brown.hstore.Jvmsnapshot.TransactionResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.brown.hstore.Jvmsnapshot.TransactionRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return edu.brown.hstore.Jvmsnapshot.TransactionResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends edu.brown.hstore.Jvmsnapshot.HStoreJVMSnapshotService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void execTransactionRequest(
          com.google.protobuf.RpcController controller,
          edu.brown.hstore.Jvmsnapshot.TransactionRequest request,
          com.google.protobuf.RpcCallback<edu.brown.hstore.Jvmsnapshot.TransactionResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.brown.hstore.Jvmsnapshot.TransactionResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            edu.brown.hstore.Jvmsnapshot.TransactionResponse.class,
            edu.brown.hstore.Jvmsnapshot.TransactionResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public edu.brown.hstore.Jvmsnapshot.TransactionResponse execTransactionRequest(
          com.google.protobuf.RpcController controller,
          edu.brown.hstore.Jvmsnapshot.TransactionRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public edu.brown.hstore.Jvmsnapshot.TransactionResponse execTransactionRequest(
          com.google.protobuf.RpcController controller,
          edu.brown.hstore.Jvmsnapshot.TransactionRequest request)
          throws com.google.protobuf.ServiceException {
        return (edu.brown.hstore.Jvmsnapshot.TransactionResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          edu.brown.hstore.Jvmsnapshot.TransactionResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_brown_hstore_TransactionRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_brown_hstore_TransactionRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_brown_hstore_TransactionResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_brown_hstore_TransactionResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"edu/brown/hstore/jvmsnapshot.proto\022\020ed" +
      "u.brown.hstore\"%\n\022TransactionRequest\022\017\n\007" +
      "request\030\001 \002(\014\"%\n\023TransactionResponse\022\016\n\006" +
      "output\030\001 \002(\0142\201\001\n\030HStoreJVMSnapshotServic" +
      "e\022e\n\026ExecTransactionRequest\022$.edu.brown." +
      "hstore.TransactionRequest\032%.edu.brown.hs" +
      "tore.TransactionResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_brown_hstore_TransactionRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_brown_hstore_TransactionRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_brown_hstore_TransactionRequest_descriptor,
              new java.lang.String[] { "Request", },
              edu.brown.hstore.Jvmsnapshot.TransactionRequest.class,
              edu.brown.hstore.Jvmsnapshot.TransactionRequest.Builder.class);
          internal_static_edu_brown_hstore_TransactionResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_brown_hstore_TransactionResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_brown_hstore_TransactionResponse_descriptor,
              new java.lang.String[] { "Output", },
              edu.brown.hstore.Jvmsnapshot.TransactionResponse.class,
              edu.brown.hstore.Jvmsnapshot.TransactionResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
